#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HelloMvx4.Droid.Resource", IsApplication=true)]

namespace HelloMvx4.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::HelloMvx4.Droid.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::HelloMvx4.Droid.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::HelloMvx4.Droid.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::HelloMvx4.Droid.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::HelloMvx4.Droid.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::HelloMvx4.Droid.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::HelloMvx4.Droid.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::HelloMvx4.Droid.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::HelloMvx4.Droid.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::HelloMvx4.Droid.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::HelloMvx4.Droid.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::HelloMvx4.Droid.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::HelloMvx4.Droid.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::HelloMvx4.Droid.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::HelloMvx4.Droid.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::HelloMvx4.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::HelloMvx4.Droid.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::HelloMvx4.Droid.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::HelloMvx4.Droid.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::HelloMvx4.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::HelloMvx4.Droid.Resource.Styleable.MvxListView_MvxItemTemplate;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f050000
			public const int header_slide_bottom_in = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int header_slide_bottom_out = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int header_slide_top_in = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int header_slide_top_out = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int slide_bottom_in = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int slide_bottom_out = 2131034117;
			
			// aapt resource value: 0x7f050006
			public const int slide_top_in = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int slide_top_out = 2131034119;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int bg = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int down_black = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int down_gray = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int down_white = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int left_black = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int left_gray = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int left_white = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ovalButton = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int right_black = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int right_gray = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int right_white = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int splash = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int up_black = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int up_gray = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int up_white = 2130837518;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080007
			public const int AddButton = 2131230727;
			
			// aapt resource value: 0x7f080005
			public const int DeleteButton = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int EditButton = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int MvvmCrossTagId = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int MvxBindingTagUnique = 2131230721;
			
			// aapt resource value: 0x7f080009
			public const int Soon = 2131230729;
			
			// aapt resource value: 0x7f080008
			public const int TextView = 2131230728;
			
			// aapt resource value: 0x7f080015
			public const int addButton = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int audioView = 2131230742;
			
			// aapt resource value: 0x7f080003
			public const int calendar = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int calendar_item_tv_day = 2131230722;
			
			// aapt resource value: 0x7f08000c
			public const int dateTextView1 = 2131230732;
			
			// aapt resource value: 0x7f080011
			public const int intervalEdit = 2131230737;
			
			// aapt resource value: 0x7f080010
			public const int intervalTextView = 2131230736;
			
			// aapt resource value: 0x7f080014
			public const int lastEditText = 2131230740;
			
			// aapt resource value: 0x7f080013
			public const int lastTextView = 2131230739;
			
			// aapt resource value: 0x7f080012
			public const int musicButton = 2131230738;
			
			// aapt resource value: 0x7f080017
			public const int musicButton1 = 2131230743;
			
			// aapt resource value: 0x7f08000a
			public const int myButton = 2131230730;
			
			// aapt resource value: 0x7f08000d
			public const int nameEditView = 2131230733;
			
			// aapt resource value: 0x7f080004
			public const int pushUp = 2131230724;
			
			// aapt resource value: 0x7f08000b
			public const int scroll = 2131230731;
			
			// aapt resource value: 0x7f08000f
			public const int timePicker = 2131230735;
			
			// aapt resource value: 0x7f08000e
			public const int timeTextView = 2131230734;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f040000
			public const int day_layout = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int FirstView = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int Main = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int SecondView = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int SplashScreen = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int ThirdView = 2130968581;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7f030000
			public const int Icon = 2130903040;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f060000
			public const int sound = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int sound1 = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int sound2 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int sound3 = 2131099651;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f090001
			public const int app_name = 2131296257;
			
			// aapt resource value: 0x7f090000
			public const int hello = 2131296256;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int AppBaseTheme = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int AppTheme = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int BaseText = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int Theme_Splash = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			public static int[] XuniCalendar;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
